nitishopshpk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from nitishop.views import index, show_data, expense_page, total_page, add_data, statistics_page, settings_page, deletedata, suppliers, del_supplier, edit_supplier, storage, del_storage, edit_storage, reset_total


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('show_data/<int:year>/<int:month>', show_data, name='show_data'),
    path('expense/', expense_page, name='expense'),
    path('budget/', total_page, name='total'),
    path('add_data/', add_data, name='add_data'),
    path('statistics/', statistics_page, name='statistics_page'),
    path('settings/', settings_page, name='settings_page'),
    path('delete/<int:o_id>/', deletedata, name='delete'),
    path('suppliers/', suppliers, name='suppliers'),
    path('del_supplier/<int:o_id>/', del_supplier, name='del_supplier'),
    path('edit_supplier/<int:supp_id>/', edit_supplier, name='edit_supplier'),
    path('storage/', storage, name='storage'),
    path('del_storage/<int:p_id>/', del_storage, name='del_storage'),
    path('edit_storage/<int:s_id>', edit_storage, name='edit_storage'),
    path('reset/', reset_total, name='reset_total'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nitishop/forms.py
from django import forms
from datetime import date
from .models import DefValues
from tempus_dominus.widgets import DatePicker

today = date.today()
d = DefValues.objects.get(id=1)
d.refresh_from_db()


class NitiShopBaseForm(forms.Form):
    date = forms.DateField(label="Data",
                           widget=DatePicker(
                               options={
                                   'format': 'DD/MM/YYYY',
                               },
                               attrs={
                                   'input_toggle': True,
                                   'input_group': True,
                                   'append': 'fa fa-calendar', 'icon_toggle': True,
                               },
                           ),
                           input_formats=('%d/%m/%Y',),
                           required=True, initial=today, )


class AddDataForm(NitiShopBaseForm):
    cashbox = forms.DecimalField(label="Arka", max_digits=9, decimal_places=2,
                                 widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    withdraw = forms.DecimalField(label="Terheqje", max_digits=9, decimal_places=2,
                                  widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

    def clean_cashbox(self):
        data = self.cleaned_data['cashbox']
        if not data:
            data = 0.00
        return data

    def clean_withdraw(self):
        data = self.cleaned_data['withdraw']
        if not data:
            data = 0.00
        return data


class AddExpenseForm(NitiShopBaseForm):
    expense = forms.DecimalField(label="Shpenzimet", max_digits=9, decimal_places=2,
                                 widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

    def clean_expense(self):
        data = self.cleaned_data['expense']
        if not data:
            data = 0.00
        return data


class DateForm(forms.Form):
    month_choices = [
        (1, 'Janar'),
        (2, 'Shkurt'),
        (3, 'Mars'),
        (4, 'Prill'),
        (5, 'Maj'),
        (6, 'Qershor'),
        (7, 'Korrik'),
        (8, 'Gusht'),
        (9, 'Shtator'),
        (10, 'Tetor'),
        (11, 'Nentor'),
        (12, 'Dhjetor'),
    ]
    this_month = forms.IntegerField(label='Muaji?',
                                    widget=forms.Select(choices=month_choices, attrs={'class': 'form-control'}), initial=today.month)
    this_year = forms.IntegerField(label='Viti?', initial=today.year,
                                   widget=forms.NumberInput(attrs={'class': 'form-control'}))


class DefaultValuesForm(forms.Form):
    wages = forms.FloatField(label="Pagat", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.wages))
    transport = forms.FloatField(label="Harxhimet e Transportit", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.transport))
    electricbill = forms.FloatField(label="Fatura e Rrymes", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.electricbill))
    internet = forms.FloatField(label="Interneti", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.internet))
    water = forms.FloatField(label="Fatura e Ujit", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.water))
    avg_percent = forms.FloatField(label="Perqindja e Fitimit", widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=float(d.avg_percent))
    
    def __init__(self, *args, **kwargs):
        g = DefValues.objects.get(id=1)
        kwargs.update(initial={
            'wages': g.wages,
            'transport': g.transport,
            'electricbill': g.electricbill,
            'internet': g.internet,
            'water': g.water,
            'avg_percent': g.avg_percent,
        })
        super(DefaultValuesForm, self).__init__(*args, **kwargs)


class SupplierForm(forms.Form):
    supplier_name = forms.CharField(label='Emri Furnitorit', widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Emri Biznesit'}), required=False)
    contact_name = forms.CharField(label='Emri Kontaktit', widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Emri i Kontaktit'}), required=False)
    tel_number = forms.CharField(label='Numri i Telefonit', widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Emri Biznesit'}), initial='+383', required=False)


class StorageForm(forms.Form):
    product_name = forms.CharField(label='Produkti', widget=forms.TextInput(
        attrs={'class': 'form-control mb-2 ml-2', 'placeholder': 'Produkti'}), required=False)
    stock = forms.IntegerField(label='Sasia', widget=forms.NumberInput(
        attrs={'class': 'form-control mb-2 ml-2', 'placeholder': 'Sasia'}), required=False)
    supp_name = forms.CharField(label='Emri Furnitorit', widget=forms.TextInput(
        attrs={'class': 'form-control mb-2 ml-2 myInput', 'placeholder': 'Emri Furnizuesit', 'id': 'myInput'}), required=True)

templates/add_data.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div class="row">
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit" class="btn btn-success">Kalkulo</button>
</form>
        </div>
        </div>
    <br>
    <hr>
{% endblock %}
    {% block table %}
    <div class="table-responsive">
    <table class="table table-bordered table-light table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Data</th>
        <th>Arka</th>
        <th>Mbetje</th>
        <th>Shitje</th>
        <th>Profit</th>
        <th>Neto</th>
    </tr>
    </thead>
    {% for i in data %}

    <tr>
    <td>{{ i.date|date:'d-m-Y' }}</td>
    <td>{{ i.cashbox }}</td>
    <td>{{ i.remain }}</td>
    <td><b>{{ i.sale }}</b></td>
    <td>{{ i.profit }}</td>
     {% if i.neto > 0 %}
    <td style="color: #16dd1c">+{{ i.neto }}</td>
      {% else %}
    <td style="color: #dd152d">{{ i.neto }}</td>
        {% endif %}
    </tr>
    {% endfor %}

    </table>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="sq">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ MEDIA_URL }}icon/logo.ico">
    <link rel="apple-touch-icon" href="{{ MEDIA_URL }}icon/apple-touch-icon.png">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    {{ form.media }}
    <style>
        body{
            padding: 0;
            margin: 0;
            background: #ebebeb;

        }
        *{
            box-sizing: border-box;
        }
        body{
            margin: 0;
            line-height: 1.5;
        }
        .table-bordered > tbody > tr > td, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > td, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > thead > tr > th {
    border: 1px solid #272727;

}
        .btn{
            border-radius: 40px;
        }
        .widget-chart{
            text-align: center;
            padding: 1rem;
            position: relative;
        }
        .card-border{
            box-shadow: 0 0 0 transparent;
            border-width: 1px;
        }
        .bg-arielle-smile{
            background: rgb(43,255,185);
background: linear-gradient(87deg, rgba(43,255,185,1) 0%, rgba(40,204,230,1) 50%, rgba(43,255,185,1) 100%);
        }
        .icon-wrapper{
            width: 54px;
            height: 54px;
            margin: 0 auto;
            position: relative;
            overflow: hidden;
            display: flex;
            align-content: center;
            align-items: center;
        }
        .icon-wrapper .icon-wrapper-bg{
            position: absolute;
            height: 100%;
            width: 100%;
            z-index: 3;
        }
        .opacity-10{
            opacity: 1!important;
        }
        .icon-wrapper i{
            margin: 0 auto;
            font-size: 29px;
            position: relative;
            z-index: 5;
        }
        .icon-gradient{

            -webkit-background-clip: text;
            -moz-background-clip: text;
            background-clip: text;
            -webkit-text-fill-color: transparent;
            text-fill-color:transparent;
        }
        .icon-wrapper i:before{
            margin-top: -3px;
        }
        .widget-chart .widget-numbers{
            font-weight: bold;
            font-size:2.95rem;
            display: block;
            line-height: 1;
            margin: 1rem auto;
        }
        .widget-chart .widget-subheading {
    margin: -0.5rem 0 0;
    display: block;
    opacity: .6;
}
        .autocomplete {
            /*the container must be positioned relative:*/
            position: relative;
            display: inline-block;
        }
        .autocomplete-items {
  position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}
.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: #fff;
  border-bottom: 1px solid #d4d4d4;
}
.autocomplete-items div:hover {
  /*when hovering an item:*/
  background-color: #e9e9e9;
}
.autocomplete-active {
  /*when navigating through the items using the arrow keys:*/
  background-color: DodgerBlue !important;
  color: #ffffff;
}
    </style>
    <title>Niti SHOP</title>
</head>
<body>
<a href="{% url 'index' %}"><img src="{{ MEDIA_URL }}logo.png" class="mb-5 mx-auto img-responsive d-block mt-4" width="135" alt="nitishop-logo"></a>
<div style="position: absolute; top: 7px; right: 5px">
    <a href="{% url 'suppliers' %}"><button class="btn btn-warning btn-md"><i class="fas fa-address-book"></i></button></a>
    <a href="{% url 'storage' %}"><button class="btn btn-info btn-md ml-1" style="background-color: #9d6b49; border-color: #7b5439"><i class="fas fa-boxes"></i></button></a>
    </div>
<div class="container">
<div class="justify-content-center mx-auto text-center">
    <div class="text-center row mx-0 justify-content-center">
    {% if request.session.fail %}
        <p style="color: #bb1b1f">{{ request.session.fail }}</p>
            {% elif request.session.success %}
            <p style="color: #2bbb34">{{ request.session.success }}</p>
        {% endif %}
    </div>
    </div>
{% block content %}

{% endblock %}
</div>

<div class="container-fluid" style="margin-top: 30px">
{% block table %}

{% endblock %}
</div>

<script type="text/javascript">
        {% block script %}
        {% endblock %}
    </script>
</body>
</html>

templates/expense.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div class="row">
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit" class="btn btn-danger">Shto Shpenzimet</button>
</form>
        </div>
        </div>

<br>
    <hr>
{% endblock %}
    {% block table %}
    <div class="table-responsive">
    <table class="table table-bordered table-light table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Data</th>
        <th>Shitje</th>
        <th>Shpenzime</th>
    </tr>
    </thead>
    {% for i in data %}

    <tr>
    <td>{{ i.date|date:'d-m-Y' }}</td>
    <td style="color: #2bbb34"><b>{{ i.sale }}</b></td>
    <td style="color: #bb1b1f"><b>{{ i.expense }}</b></td>
    </tr>
    {% endfor %}

    </table>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="justify-content-center mx-auto text-center">
    <div class="text-center row mx-0 justify-content-center">

    <a href="{% url 'add_data' %}"><button type="button" class="btn btn-lg btn-outline-success py-3 px-4 ml-3 mb-4"><i class="fas fa-cart-arrow-down"></i></button></a>

    <a href="{% url 'expense' %}"><button type="button" class="btn btn-lg btn-outline-danger py-3 px-4 ml-3 mb-4"><i class="fas fa-file-invoice-dollar"></i></button></a>

    <a href="{% url 'statistics_page' %}"><button type="button" class="btn btn-lg btn-outline-info py-3 px-4 ml-3 mb-4"><i class="fas fa-chart-area"></i></button></a>

    <a href="{% url 'total' %}"><button type="button" class="btn btn-lg btn-outline-info py-3 px-4 ml-3 mb-4"><i class="fas fa-wallet"></i></button></a>
    </div>
    </div>


    <div class="row justify-content-center text-center">
    <div class="justify-content-center text-center">
    <form method="post" class="form-inline justify-content-center">
        <div class="form-group">
        {% csrf_token %}
        {{ form }}
        </div>
    <button type="submit" class="btn btn-primary">Kerko!</button>
    </form>
    </div>
    </div>
<br>
    <div class="justify-content-center mx-auto text-center">
    <div class="text-center row mx-0 justify-content-center">

        <a href="{% url 'settings_page' %}"><button type="button" class="btn btn-md btn-dark py-3 px-4 ml-3 mb-4"><i class="fas fa-cog"></i></button></a>

    </div>
    </div>

    <hr>
{% endblock %}


{% block table %}
    <div class="table-responsive">
    <table class="table table-bordered table-light table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Data</th>
        <th>Arka</th>
        <th>Terheqje</th>
        <th>Mbetje</th>
        <th>Shitje</th>
        <th>Profit</th>
        <th>Neto</th>
        <th>Shpenzime</th>
        <th>Del?</th>
    </tr>
    </thead>
    {% for i in data %}

    <tr>
    <td>{{ i.date|date:'d-m-Y' }}</td>
    <td>{{ i.cashbox }}</td>
    <td>{{ i.withdraw }}</td>
    <td>{{ i.remain }}</td>
    <td><b>{{ i.sale }}</b></td>
    <td>{{ i.profit }}</td>
     {% if i.neto > 0 %}
    <td style="color: #16dd1c">+{{ i.neto }}</td>
      {% else %}
    <td style="color: #dd152d">{{ i.neto }}</td>
        {% endif %}
    <td>{{ i.expense }}</td>
    <td><a href="{% url 'delete' o_id=i.pk %}"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button> </a> </td>
    </tr>
    {% endfor %}

    </table>
    </div>
{% endblock %}

templates/settings.html
{% extends 'base.html' %}

{% block content %}

    <div class="row ">
<div class="col text-center">
    <h5>Mujore: <span style="background-color: #aeffe4">{{ data.total_exp }}</span></h5>
</div>
    <div class="col text-center">
        <h5>Dita: <span style="background-color: #aeffe4">{{ data.day_expense }}</span></h5>
</div>
    </div>

    <div class="d-flex justify-content-center">

    <div class="row">
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit" class="btn btn-dark">Ruaj</button>
</form>
        </div>
        </div>
    <br>
    <hr>
{% endblock %}

templates/show_data.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="bg-light text-center">Informatat e gjeneruara te muajit: <b>{{ month }}</b></h1>
{% endblock %}

{% block table %}
    <div class="table-responsive">
    <table class="table table-bordered table-light table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Data</th>
        <th>Arka</th>
        <th>Terheqje</th>
        <th>Mbetje</th>
        <th>Shitje</th>
        <th>Profit</th>
        <th>Neto</th>
        <th>Shpenzime</th>
    </tr>
    </thead>
    {% for i in data %}

    <tr>
    <td>{{ i.date|date:'d-m-Y' }}</td>
    <td>{{ i.cashbox }}</td>
    <td>{{ i.withdraw }}</td>
    <td>{{ i.remain }}</td>
    <td><b>{{ i.sale }}</b></td>
    <td>{{ i.profit }}</td>
     {% if i.neto > 0 %}
    <td style="color: #16dd1c">+{{ i.neto }}</td>
      {% else %}
    <td style="color: #dd152d">{{ i.neto }}</td>
        {% endif %}
    <td>{{ i.expense }}</td>
    </tr>
    {% endfor %}

    </table>
    </div>
{% endblock %}

templates/statistics.html
{% extends 'base.html' %}
{% block table %}
<h1 class="bg-light text-center">Statistikat:</h1>
    <br>
<div class="row ">
<div class="col text-center">
<h3>Ky Muaj:</h3>
    <table class="table table-bordered table-light table-hover">
        <tr>
        <th class="bg-dark text-light">Muaji:</th>
            <td style="background-color: #cbfaf2;"><b>{{ this_date }}</b></td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Shitje</th>
            <td>{{ sale }}{% if sale > sale1 %}
                <i class="fas fa-chevron-up" style="color: #16DD1C"></i>
                {% else %}
                <i class="fas fa-chevron-down" style="color: #dd152d"></i>
            {% endif %}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Profit</th>
            <td>{{ profit }}{% if profit > profit1 %}
                <i class="fas fa-chevron-up" style="color: #16DD1C"></i>
                {% else %}
                <i class="fas fa-chevron-down" style="color: #dd152d"></i>
            {% endif %}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Neto</th>
            <td>{{ neto }}{% if neto > neto1 %}
                <i class="fas fa-chevron-up" style="color: #16DD1C"></i>
                {% else %}
                <i class="fas fa-chevron-down" style="color: #dd152d"></i>
            {% endif %}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Terheqje</th>
            <td>{{ withdraw }}{% if withdraw > withdraw1 %}
                <i class="far fa-smile-wink" style="color: #16DD1C"></i>
                {% else %}
                <i class="far fa-frown" style="color: #dd152d"></i>
            {% endif %}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Shpenzim</th>
            <td>{{ expense }}</td>
        </tr>

    </table>
</div>
<div class="col text-center">
    <h3>Muaji i Kaluar:</h3>
    <table class="table table-bordered table-light table-hover">
        <tr>
        <th class="bg-dark text-light">Muaji:</th>
            <td style="background-color: #e7defa;"><b>{{ prev_date }}</b></td>
        </tr>
        <tr>
            <tr>
            <th class="bg-dark text-light">Shitje</th>
            <td>{{ sale1 }}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Profit</th>
            <td>{{ profit1 }}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Neto</th>
            <td>{{ neto1 }}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Terheqje</th>
            <td>{{ withdraw1 }}</td>
        </tr>
        <tr>
            <th class="bg-dark text-light">Shpenzim</th>
            <td>{{ expense1 }}</td>
        </tr>

    </table>
</div>
</div>
{% endblock %}

templates/suppliers.html
{% extends 'base.html' %}

{% block script %}
$(document).ready(function(){
  $("#searching").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#table-content tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
{% endblock %}

{% block content %}
    {% if request.session.msg %}
    <!--suppress ALL -->
        <p style="color: #2bbb34" class="text-center">{{ request.session.msg }}</p>
    {% endif %}
    <div class="d-flex justify-content-center">
    <div class="row">
<form method="POST" class="text-center">
    {% csrf_token %}
   {{ form.supplier_name }}
    {{ form.contact_name }}
    {{ form.tel_number }}
              <button type="submit" class="btn btn-success">Ruaj</button>
</form>
        </div>
        </div>
    <br>
    <h3 class="text-center">Kerko...</h3>
    <input type="search" class="form-control search-input" id="searching" placeholder="Kerko Kontaktin">
    <hr>
{% endblock %}
    {% block table %}
    <div class="table-responsive">
    <table class="table table-bordered table-light table-hover customers-list">
    <thead class="thead-dark">
    <tr>
        <th>Emri Biznesit</th>
        <th>Emri Kontaktit</th>
        <th>Numri i Telefonit</th>
        <th>Thirre?</th>
        <th>Fshije?</th>
    </tr>
    </thead>
    <tbody id="table-content">
    {% for i in data %}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ndrysho te dhenat</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'edit_supplier' supp_id=i.id %}" method="post">
            {% csrf_token %}
            <input type="text" name="supplier_name" class="form-control" placeholder="Emri Biznesit" required="" id="id_supplier_name" value="{{ i.supplier_name }}">
    <input type="text" name="contact_name" class="form-control" placeholder="Emri i Kontaktit" required="" id="id_contact_name" value="{{ i.contact_name }}">
    <input type="text" name="tel_number" value="{{ i.tel_number }}" class="form-control" placeholder="Emri Biznesit" required="" id="id_tel_number">

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Mbyll</button>
        <button type="submit" class="btn btn-primary">Ruaj</button>
          </form>
      </div>
      </div>
    </div>
  </div>
</div>
    <tr>
        <td>{{ i.supplier_name }}</td>
    <td>{{ i.contact_name }}</td>
    <td><a href="tel:{{ i.tel_number }}">{{ i.tel_number }}</a></td>
    <td style="padding: 5px" class="justify-conent-center text-center"><a href="tel:{{ i.tel_number }}"><button class="btn btn-success btn-md"><i class="fas fa-phone"></i></button></a></td>
    <td style="padding: 5px" class="justify-conent-center text-center"><a href="{% url 'del_supplier' o_id=i.id %}"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></a> <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-edit"></i></button> </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>





{% endblock %}

templates/total.html
{% extends 'base.html' %}
<!--<td>{ i.date|date:'d-m-Y' }}</td>-->

{% block table %}
<h1 class="text-center" style="background: #fff;">Total</h1>
    <br>

    <div class="row">
<div class="col text-center" style="border-right: 2px solid #c7c7c7">
<h3>Shitje:</h3>
    <h3 style="background: #aeffe4;">{{ sale }}&euro;</h3>
    <hr>
</div>

<div class="col text-center">
    <h3>Profit:</h3>
    <h3 style="background: #acdeff;">{{ profit }}&euro;</h3>
    <hr>
</div>
 </div>
    <div class="row">
<div class="col text-center" style="border-right: 2px solid #c7c7c7">
<h3>NETO:</h3>
    <h3 style="background: #aeffb1;">{{ neto }}&euro;</h3>
    <hr>
</div>

<div class="col text-center">
    <h3>Shpenzime:</h3>
    <h3 style="background: #ffc7b9;">{{ expense }}&euro;</h3>
    <hr>
</div>
 </div>
    <br>
    <br>
    <div class="row">
    <div class="col-md">
        <div class="card mb-3 bg-arielle-smile widget-chart text-white card-border">
            <div class="icon-wrapper rounded-circle">
                <div class="icon-wrapper-bg bg-white opacity-10"></div>
                <i class="fas fa-euro-sign lnr-cog icon-gradient bg-arielle-smile"></i></div>
    <div class="widget-numbers">{{ budget }}</div>
        <div class="widget-subheading">Buxheti</div>
</div>
    </div>
    </div>
{% endblock %}